// <auto-generated />
namespace EFStudent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSATandGPA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSATandGPA));
        
        string IMigrationMetadata.Id
        {
            get { return "201802221721356_Add SAT and GPA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
